### PR TITLE
Add a server side timeout

### PR DESCRIPTION
**Pull request by matthewsowders**
Adding a url parameter timeoutMillis and a default configurable value scriptTimeoutMillis.  The timeoutMillis overrides the configured scriptTimeoutMillis value.  This server side timeout can prevent scripts from accidentally taking down the server by consuming all resources in an infinite loop.

### CODE REVIEW

**Comment by spmallette** [comment]
This is a nice feature and something we have in the successor to Rexster in TinkerPop3, Gremlin Server:

http://tinkerpop.incubator.apache.org/docs/3.0.0.M9-incubating/#gremlin-server

I'm not sure if I'm missing something or not, but it appears that this feature only applies to the web console UI in Dog House.  It's not applying to the REST-based [Gremlin Extension](https://github.com/tinkerpop/rexster/wiki/Gremlin-Extension) or to [RexPro](https://github.com/tinkerpop/rexster/wiki/RexPro).  I'm not terribly concerned about RexPro, as it has a different set of configuration, but I think that to have the `scriptTimeoutMillis` would mean that it would be expected that this work with all things HTTP (i.e.Gremlin Extension AND Dog House).  I guess that's my first concern with this PR.

My second concern is this: 

https://github.com/tinkerpop/rexster/pull/388/files#diff-763a5b2f55650616c24b81b8715df554L54

where you drop a single thread for a shared `ExecutorService`:

https://github.com/tinkerpop/rexster/pull/388/files#diff-763a5b2f55650616c24b81b8715df554R38

My interpretation of that change cause me some concern.  A "session" needs to be bound to a single thread.  If it is not, transactional graphs which tend to rely on `ThreadLocal` for maintaining their transactional context will not work properly in Rexster.  In other words, this change makes it possible for two requests to the same session to be processed by two different threads which means that in the same session you would end up with two different transactions.  Does that make sense?

If so, you could probably solve it with a single threaded `ExecutorService` bound to the session:

http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newSingleThreadExecutor()

Those were the two things that kinda popped out at me as I looked at this.  Not sure if there's other things, but if you want to try to resolve these issues and re-submit, I'd be happy to look again.

Please note that development on Rexster has largely ceased given the eminent release of TinkerPop3 and Gremlin Server.  We're mostly focused on "bug fix" type pull requests at this point across all of TinkerPop 2.x, but given the usefulness of this feature and the lack of workarounds for the problem, I'm good with working this through with you if you so desire.

Also, if I might ask, what kinds of things are you doing with Rexster that made you dig into it in enough detail to offer this PR?

**Comment by matthewsowders** [comment]
I'm not familiar with the entry points for the REST-based Gremlin Extension, RexPro or Gremlin Server, but I'd be happy to add it to them if you think it useful.  Could you point me to the code in the appropriate project/branch? 

Each "session" has a single scriptEngine that is synchronized by scriptEngineLock.  That should ensure that any session is only running in a single thread at a time.  One thing I did miss though is that I forgot to call 'cancel' on the future after an exception.

I was working with someone that found their Rexster server was sometimes passed queries that would get stuck in an infinite loop when traversing a graph so they would have to bounce the server.  It was easy enough to find where the gremlin script was executed and wrap it in new Java features that allow for timeouts.

**Comment by spmallette** [comment]
> I'm not familiar with the entry points for the REST-based Gremlin Extension

Don't worry about Gremlin Server in TP3 - we have multiple timeout configuration options there.  For this PR, I think it's just worth focusing on making sure that your timeout capability works in the various places `eval` is called in this class (which should be easier to implement that the stuff you started with in sessions):

https://github.com/tinkerpop/rexster/blob/master/rexster-server/src/main/java/com/tinkerpop/rexster/gremlin/GremlinExtension.java#L275

This problem of "timeout" tends to get fairly involved by the way.  Right now you have an "eval" based timeout, but result iteration is equally a problem in some respects.  I can issue some fatty Gremlin like:  `g.V()` which will immediately return from `eval()` but on a billion edge graph take forever to iterate/serialize and thus bypass your timeout feature.  Not saying you necessarily need to do anything about that for this PR, but just wanted to point it out.

Actually - now i'm a little confused as I look at this again.  Your timeout doesn't really interrupt the evaluation it just timesout waiting for the script to finish eval right?

https://github.com/matthewsowders/rexster/blob/timeout/rexster-server/src/main/java/com/tinkerpop/rexster/gremlin/GremlinSession.java#L85

I mention that in reference to this:

> One thing I did miss though is that I forgot to call 'cancel' on the future after an exception.

Will you be able to make it so that script eval will actually stop processing?  To my knowledge, `ScriptEngine.eval()` doesn't respond to that so well.

With respect to:

> Each "session" has a single scriptEngine that is synchronized by scriptEngineLock. That should ensure that any session is only running in a single thread at a time.

You might have misunderstood me or perhaps I'm misunderstanding you, but I wasn't saying that you needed to have a session "only running in a single thread at a time".  What I meant was, a session needs to execute in the same thread on every request.  You have to bind the session to a single thread of execution.  In other words, in a session, you can't have request 1 get processed by thread A and then have request 2 get processed in thread B.  If request 1 started the session in thread A then every single request following the first in that session must occur on thread A.  If you don't do that - weird things happen with transactions.  Did I explain better that time?

> I was working with someone that found their Rexster server was sometimes passed queries that would get stuck in an infinite loop when traversing a graph so they would have to bounce the server.

I've not heard of anyone passing queries directly to the `EvaluatorServlet` (but it wouldn't surprise me).  That feature is largely just there to support the Dog House web UI, but I suppose folks could re-purpose it to their own ends, but it is definitely for "internal" use.  Most people submit Gremlin queries over REST to the Gremlin Extension I provided the link to above.  Requests made to the Gremlin Extension are considered sessionless - as REST should be - which saves the complications of trying to bind sessions to threads and what not.  

I hope that your colleague working with Rexster will consider checking out Gremlin Server and TinkerPop3.  I like to think that it is a great improvement on top of Rexster with a much more streamlined approach.

**Comment by matthewsowders** [comment]
Thank you.  I'll take a look at GremlinExtension and get back to you.

> Your timeout doesn't really interrupt the evaluation it just timesout waiting for the script to finish eval right? 
Yes.  That is why I mentioned needing to change the code to call cancel on the future upon an exception.  

> Will you be able to make it so that script eval will actually stop processing? To my knowledge, ScriptEngine.eval() doesn't respond to that so well.
I imagine that to be the case, but a timeout is likely due to a larger problem like a loop in the graph and a query that does not handle it.  What do you mean by 'doesnt respond to that so well'? Do you mean that the ScriptEngine is in an unknown state after an interrupt and should not be used again?

> a session needs to execute in the same thread on every request
Ok.  I misunderstood.  If this is the case, are you not able to load balance because that would result in not only not being on the same thread, but not on the same host either.  If there are threadlocals set and not cleaned up between requests, doesn't that leave the system open for a memory leak?

>If you don't do that - weird things happen with transactions
Is that implementation specific or do you feel this has to be the lowest common denominator? https://github.com/tinkerpop/blueprints/wiki/Graph-Transactions mentions ways of handling transactions across multiple threads.

> Gremlin Server in TP3 - we have multiple timeout configuration options there
Do you get around the ScriptEngine.eval timeout problems you mentioned earlier in your new version?

**Comment by spmallette** [comment]
> Yes. That is why I mentioned needing to change the code to call cancel on the future upon an exception.

I'm trying to say that even with a call to `cancel` it doesn't interrupt the `eval()`.  Calling `cancel` on a `Future` (from the javadoc):

> Attempts to cancel execution of this task. This attempt will fail if the task has already completed, has already been cancelled, or could not be cancelled for some other reason. If successful, and this task has not started when cancel is called, this task should never run. If the task has already started, then the mayInterruptIfRunning parameter determines whether the thread executing this task should be interrupted in an attempt to stop the task.

So you call `cancel` with `true` to interrupt the thread, but even if you "interrupt" the running thread, the code in the thread has to respond to the interruption...and `eval()` doesn't.  So, when I say "doesn't respond to that so well", I just meant that once the thread starts processing the job and gets into `eval` it will typically consume that thread until you're out of `eval` (though you'll free the servlet thread from blocking while waiting to provide a response which is kinda nice, but if someone issues a `while(true){}` that thread in your `ExecutorService` is consumed for good. 

Here's an example using the Gremlin Console (with TP3 syntax):

```text
gremlin> :import java.util.concurrent.*
==>groovy.grape.Grape, org.apache.commons.configuration.*, org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.*, 
...
org.apache.tinkerpop.gremlin.tinkergraph.process.computer.*, java.util.concurrent.*
gremlin> 
gremlin> graph = TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> v = graph.addVertex()
==>v[0]
gremlin> v.addEdge('self',v)
==>e[1][0-self->0]
gremlin> g = graph.traversal()
==>graphtraversalsource[tinkergraph[vertices:1 edges:1], standard]
```

So above creates a graph with one vertex with a self-referencing edge.  

```text
gremlin> service = Executors.newSingleThreadExecutor()
==>java.util.concurrent.Executors$FinalizableDelegatedExecutorService@17ae98d7
```

Next I create a `ExecutorService` with a single thread to handle some jobs i submit.  Then we need a traversal that will executor "forever" (which is what you're trying to prevent with your timeout): `g.V(0l).repeat(out()).times(Integer.MAX_VALUE)`  Basically, get vertex "0" then traverse `out` until we exhaust that path or we hit `Integer.MAX_VALUE` - obviously we have a cycle in the graph so it will just go on until `Integer.MAX_VALUE` which would tie up Rexster quite nicely.

Next we create two jobs (groovy closures can be represented as `Callable`):

```text
gremlin> job1 = { g.V(0l).repeat(out()).times(Integer.MAX_VALUE).toList() }
==>groovysh_evaluate$_run_closure1@126be319
gremlin> job2 = { 1+1 }
==>groovysh_evaluate$_run_closure1@aa5455e
```

The first job has our super-long and Rexster crushing one and the second is super simple to return in millseconds after `eval`.  So we submit them both to the `ExecutorService`:

```text
gremlin> f1 = service.submit(job1 as Callable)
==>java.util.concurrent.FutureTask@4fdf8f12
gremlin> f2 = service.submit(job2 as Callable)
==>java.util.concurrent.FutureTask@450794b4
```

Now let's see what's done:

```text
gremlin> f1.isDone()
==>false
gremlin> f2.isDone()
==>false
gremlin> f1.isDone() // a few seconds later
==>false
gremlin> f1.isDone()  // a few more seconds later
==>false
```

Clearly, as expected `f1`

```text
gremlin> f1.cancel(true)
==>true
gremlin> f1.isDone()
==>true
gremlin> f2.isDone()
==>false
gremlin> f1.get()
java.util.concurrent.CancellationException
Display stack trace? [yN] n
gremlin> f2.get()
```



I wasn't sure if you had some neat way to deal with that or not.

>  If this is the case, are you not able to load balance because that would result in not only not being on the same thread, but not on the same host either. If there are threadlocals set and not cleaned up between requests, doesn't that leave the system open for a memory leak?

This is why we tend to recommend that users utilize "sessionless" requests for production applications. The only reason we have sessions in Rexster was to support Dog House/Rexster Console which are two very lightweight features and for non-jvm languages that want to have complete control of transactions (in which case they carry the risk/burden of those things you mentioned).  

> Is that implementation specific or do you feel this has to be the lowest common denominator? https://github.com/tinkerpop/blueprints/wiki/Graph-Transactions mentions ways of handling transactions across multiple threads.

I don't know of any graph implementations that support transactions that don't work this way.  Titan is the only graph to support "Threaded Transactions" (which is what I assume you are referencing in that link) and Rexster isn't the right use case for that.  You use that kind of transaction when you want multiple threads to share the same transaction.  Not so good in the context of what we're discussing here with sessions right?  It's good that request 1 and request 2 in session 1 could operate on two different threads in the same transaction, but not so good that request 1 and request 2 in session 2 would also be in that same transaction.  

> Do you get around the ScriptEngine.eval timeout problems you mentioned earlier in your new version?

Gremlin Server is not completely bulletproof, but we have ways to prevent the worst stuff people can do.  We timeout both eval and result iteration/serialization process (we can actually interrupt the latter properly).  We handle the eval limitations with different AST transformations (e.g. auto-inject code to respond to interrupt requests where it is possible to do so) and TP3 `TraversalStrategy` implementations.  Again not completely bulletproof, but better than Rexster.  

I would not want to backport much of that to Rexster - it's not jot worth the time and code maintenance costs given that Gremlin Server is so near release.  If you'd like to see this PR in place

**Comment by spmallette** [comment]
I edited my previous comment a few times - you might want to read it on GitHub rather than in the email notification.

**Comment by matthewsowders** [comment]
Thanks for taking the time to explain in such detail.  I appreciate it. 

I could go back and update the executor to single thread as you mentioned, but I'm not sure if it is worth the change if we cannot stop the executing thread.  What do you think?  

I'd like to learn more about your approach in the new gremlin server.  Could you point me to the code to learn more about your approach to timeout?

**Comment by spmallette** [comment]
tbh, i think this pull request only makes sense if there is something novel introduced around cancellation.  so probably not worth it, especially since Rexster is being wholly replaced.  

For Gremlin Server, you probably should start by looking at (which eval's incoming Gremlin):

https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java#L136

and this important class:

https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java

and finally the construction of the script compiler in our custom gremlin scriptengine implementation:

https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java

Would be great to see some pull requests from you on the TP3 side of the world  :smile:

**Pull request closed without merging**
