### PR TITLE
Corrected typos

### PR DESCRIPTION
**Pull request by kevinisaac**

### CODE REVIEW

**Comment by spmallette** [comment]
Merged - thanks.

**Comment by spmallette** [comment]
Actually - damn - that wasn't the way to fix that. Those pages are archives of the github wiki.  I went and made that edit manually.  Oh well - guess it didn't hurt anything.

**Comment by kevinisaac** [comment]
Oops. Sorry, didn't know how to contribute to the wiki. So, I thought changing the doc file would do the trick.

Do I need commit access to the wiki repo? I'm not sure how to create a pull request for the wiki git repo. I have the commit locally after cloning the wiki, but can't push.

**Comment by spmallette** [comment]
not your fault by any means....i just edited the wiki manually with your change.  you should see it there now.  let me know if i missed something.

**Comment by kevinisaac** [comment]
Yep, one thing. Just replace `cache-scripts>` with `<cache-scripts>`.

**Comment by spmallette** [comment]
fixed - thanks.

**Pull request merged**
